### ISSUE TITLE
issue with payload 2.0 

### ISSUE THREAD

**Issue by beewhoo** [thgh/payload-plugin-oauth#13]
getting this error when updating from payload 2.0, is this a breaking change? 

npm ERR! Could not resolve dependency:
npm ERR! peer payload@"^1" from payload-plugin-oauth@0.3.1

**Comment by thgh** [comment]
Haven't tested with payload 2. You could ignore the error and see if it works.

**Comment by beewhoo** [comment]
doesn't seem to work even when forcing,  here is a full trace 

```
Could not resolve dependency:
npm ERR! peer payload@"^1" from payload-plugin-oauth@0.3.1
npm ERR! node_modules/payload-plugin-oauth
npm ERR!   payload-plugin-oauth@"^0.3.0" from payload-cms@1.0.0
npm ERR!   apps/payload-cms
npm ERR!     payload-cms@1.0.0
npm ERR!     node_modules/payload-cms
npm ERR!       workspace apps/payload-cms from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/beewhoo/.npm/_logs/2023-10-17T22_18_50_655Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/beewhoo/.npm/_logs/2023-10-17T22_18_50_655Z-debug-0.log
```

**Comment by thgh** [comment]
How about https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides ?

**Comment by WilsonLe** [comment]
I added payload v2 compatibility here, with some extra changes to allow more control over the plugin (i.e customizable `express-session` options, customizable `options.customAuthorizePath`)

#14
