### ISSUE TITLE
NPM publishing went wrong

### ISSUE THREAD

**Issue by Samtropic** [thgh/payload-plugin-oauth#18]
Hello,
Something went wrong when publishing the last version on npm, you ended up with an ancient version of the code as you can see in the screenshot.

![image](https://github.com/thgh/payload-plugin-oauth/assets/127030009/2137f4f2-6624-49e9-a409-2db31b2014ad)

**Comment by thgh** [comment]
Woops, fixed in v2.1.1

Added prepare script so it rebuilds always before publish.
