### ISSUE TITLE
Add id or class to button to allow for styling

### ISSUE THREAD

**Issue by bertPB** [thgh/payload-plugin-oauth#20]
Thanks for making this plugin, it's been really useful to me so far!
I was wondering if it is possible to pass styles to the auth button?
Maybe you could add a class or id (or allow us to set the class/id in the config) to the OAuthButton component to allow for styling overrides?

**Comment by thgh** [comment]
You can adjust the button like this:

```tsx

import Button from 'payload/dist/admin/components/elements/Button'

// payload.config.ts
oAuthPlugin({
  components: {
    Button: () => (
      <div style={{ marginBottom: 40 }} className="custom">
        <Button el="anchor" url="/oauth/authorize">
          Sign in
        </Button>
      </div>
    )
  },
  ...rest,
}),
```

Note that in the next plugin version the button component receives props: (not available in v2.1)
https://github.com/thgh/payload-plugin-oauth/blob/e0a6b6e71d7acf56d5fc76b5e91fa1513f0eeacb/src/types.ts#L73-L78
